name: Validate Process
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
      - name: G11n Radar
        uses: citrix-workspace/g11n-scan@action-dev
        with:
          access-token: ${{ secrets.GITHUB_TOKEN }}
          skip: 'bundles/coming_soon/,bundles/dip/Citrix/com.sapho.services.zendesk.ZendeskService/'

